@startgantt p2a_gantt
<style>
ganttDiagram {
  FontName Montserrat
  milestone {
    FontStyle bold
  }
  arrow {
    LineColor #808080
  }
}
</style>

language nl

Project starts 2026-02-09
projectscale weekly with week numbering from 1

[1A: Literatuurstudie                   ] starts 2026-02-09 and ends 2026-03-27
[1A: Literatuurstudie                   ] is colored in #FABC32

[1B: Evaluatie beschikbare tools] starts 2026-02-09 and ends 2026-02-20
[1B: Evaluatie beschikbare tools] is colored in #FABC32

[2: Ontwerp manuele testomgeving] starts 2026-02-23 and ends 2026-03-13
[2: Ontwerp manuele testomgeving] is colored in #4CA2D5
[2: Ontwerp manuele testomgeving] starts after [1B: Evaluatie beschikbare tools]'s end

[Indienen eerste draft BP (02/03/2026)] happens 2026-03-02
[Indienen eerste draft BP (02/03/2026)] is colored in #EF8767

[3A: Implementatie manuele testomgeving] starts 2026-03-16 and ends 2026-03-27
[3A: Implementatie manuele testomgeving] is colored in #A5CA72
[3A: Implementatie manuele testomgeving] starts after [2: Ontwerp manuele testomgeving]'s end

[3B: Opstellen testcases] starts 2026-03-16 and ends 2026-04-17
[3B: Opstellen testcases] is colored in #A5CA72
[3B: Opstellen testcases] starts after [2: Ontwerp manuele testomgeving]'s end

[4: Ontwikkeling Proof of Concept       ] starts 2026-03-30 and ends 2026-05-22
[4: Ontwikkeling Proof of Concept       ] is colored in #BB90BD
[4: Ontwikkeling Proof of Concept       ] starts after [1A: Literatuurstudie                   ]'s end
[4: Ontwikkeling Proof of Concept       ] starts after [3A: Implementatie manuele testomgeving]'s end

[5: Uitvoeren testcases] starts 2026-04-20 and ends 2026-05-22
[5: Uitvoeren testcases] is colored in #F19DA0
[5: Uitvoeren testcases] starts after [3B: Opstellen testcases]'s end

[Indienen finale draft BP (04/05/2026)] happens 2026-05-04
[Indienen finale draft BP (04/05/2026)] is colored in #EF8767

[Indienen bachelorproef (29/05/2026)] happens 2026-05-29
[Indienen bachelorproef (29/05/2026)] is colored in #EF8767

@endgantt