@startuml test_env

set separator .
left to right direction

node web {
    component apache_exporter
    component dns_client
    component mysqld_exporter
    component node_exporter
    component web_server
}

node dns {
    component bind_exporter
    component dns_client
    component dns_server_primary
    component node_exporter
}

node mon as "monitoring" {
    component dns_client
    component monitoring_server
    component node_exporter
}

dns.dns_client -[#teal]-> dns.dns_server_primary

mon.dns_client -[#teal]-> dns.dns_server_primary
mon.monitoring_server -[#coral]-> dns.bind_exporter
mon.monitoring_server -[#coral]-> dns.node_exporter
mon.monitoring_server -[#coral]-> mon.node_exporter
mon.monitoring_server -[#coral]-> web.apache_exporter
mon.monitoring_server -[#coral]-> web.mysqld_exporter
mon.monitoring_server -[#coral]-> web.node_exporter

web.dns_client -[#teal]-> dns.dns_server_primary

@enduml