@startnwdiag test_env

network test.lan {
  address = "172.26.0.0/16"

  web [address = "172.26.0.10", shape = "node"]
  dns [address = "172.26.0.20", shape = "node"]
  mon [description = "monitoring", address = "172.26.0.30", cpus = 2, memory = 2048, shape = "node"]
}

@endnwdiag
