# ansible/inventory.yml
---
all:
  vars:
    ansible_user: vagrant
    ansible_ssh_password: vagrant
    ansible_become: true
  children:
    test.lan:
      hosts:
        web:
          ansible_host: 172.26.0.10
        dns:
          ansible_host: 172.26.0.20
        monitoring:
          ansible_host: 172.26.0.30
